### PR TITLE
PR for code review - Redux setup

### PR DESCRIPTION
**Pull request by wickathou**
This PR features Redux implemented with Vite+React+Tailwind for the bookstore app

**Features**
- Added Redux store
- Added uuid for unique identification generation
- Added folder structure following Ducks pattern

[Live view](https://wickathou.github.io/bookstore-app/)

### CODE REVIEW

**Review by Olamarx — APPROVED** [review]
Hi @wickathou, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Redux toolkit ✔️
- createStore and configureStore ✔️
- Professional readme file ✔️
- Linter setup ✔️

## Required Changes ♻️
_Check the comments under the review._
- [x] While you have done a wonderful job, all that is left is your MIT link, it is broken, kindly fix it.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wickathou** [comment]
Hey @Olamarx I merged because your previous message said all was approved. I just updated the License link and now it works.

Here's the link
https://github.com/wickathou/bookstore-app/blob/dev/LICENSE

**Comment by Olamarx** [comment]
@wickathou I am very sorry, I initially approved it but I forgot about the MIT, you can ask for a second opinion or you request for review again. My mistake, my apologies.

**Review by Lucas-Masaba — COMMENTED** [review]
# Hello @wickathou  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

almost-there

## Highlights 🍾 
- Made changes as requested by the previous reviewer 👍 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
